import Logic.Node;
import Logic.WordCounter;

public class Main {

    public static void main(String[] args) {


        count("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at condimentum odio, nec tincidunt arcu. Maecenas velit odio, ultrices id erat id, mattis hendrerit tortor. Duis nec vehicula ante. Proin vel nibh id eros rutrum mattis ac vitae mi. Sed est lacus, tristique nec aliquet ultrices, fermentum in leo. Quisque eu tempus magna. Donec laoreet, erat et bibendum pharetra, sapien lectus auctor nibh, vel consequat ex eros vestibulum dolor. Cras placerat turpis eget metus porta pretium. Sed eget lorem non ipsum finibus pharetra in non enim. Aenean porta, purus vel gravida consequat, mauris risus aliquet purus, nec tempor lorem leo ac dolor.\n" +
                "\n" +
                "Vestibulum hendrerit massa dui, id finibus est sollicitudin in. Ut non lacus eget turpis ultricies varius vel a purus. Donec viverra bibendum mauris eget sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam egestas lorem quis nibh varius, sed ullamcorper orci ullamcorper. Morbi varius posuere tellus, vitae pretium augue rutrum eget. Vivamus in tortor non sapien ultrices lobortis. Maecenas sem dolor, suscipit a consectetur at, feugiat eget neque. Pellentesque bibendum nulla risus, quis dictum mi porttitor non. Aenean ac ultrices nisl. Pellentesque fringilla libero lorem, vel porta tortor tincidunt at. Pellentesque imperdiet non nunc ut sollicitudin. Pellentesque nec ante tellus. Suspendisse ultrices felis vel nibh lacinia mattis. Sed lacinia neque in tincidunt dignissim.\n" +
                "\n" +
                "Integer porta pellentesque risus, quis consequat neque varius nec. Morbi viverra augue id lacus facilisis pulvinar. Nulla facilisi. Aliquam blandit efficitur mi. Fusce lacinia nisl eu ex gravida, a facilisis lectus lacinia. Phasellus interdum maximus feugiat. Etiam at mauris a massa ullamcorper consectetur. Pellentesque imperdiet libero eu porta commodo. Morbi et vehicula elit. Nam et sapien ac diam eleifend dictum. Etiam congue faucibus est id semper. Proin tempus arcu in sollicitudin elementum. Cras finibus elit eget sagittis semper.\n" +
                "\n" +
                "Pellentesque nec hendrerit nisl. Nulla et egestas mi. Pellentesque sed erat ornare, tincidunt ante ac, auctor dui. Duis hendrerit orci eu odio vulputate consectetur. Donec sit amet ultricies turpis, eget aliquam nibh. Nam quam dui, ullamcorper nec consequat vitae, dictum ac nunc. Nunc volutpat massa sed metus finibus, vitae faucibus ipsum vehicula. Nunc a mi eget enim egestas convallis. Proin venenatis est eu sollicitudin cursus. Vestibulum ultricies, turpis ac elementum dictum, sem dolor elementum elit, ut tristique nulla est at libero. Mauris vel iaculis ipsum.\n" +
                "\n" +
                "Suspendisse accumsan tortor turpis, nec egestas lacus condimentum eu. Integer sodales ornare sapien, sit amet luctus justo porta efficitur. Nunc sit amet placerat ex. Pellentesque dignissim, tellus in aliquet vehicula, massa dolor pulvinar lacus, vitae ullamcorper risus nunc ac orci. Nam et mattis libero. Duis lacinia velit lacus, a semper felis tincidunt vel. Proin euismod hendrerit arcu, sed pretium metus interdum vel.\n" +
                "\n" +
                "Sed condimentum velit a lorem vulputate, non consequat lorem viverra. Vestibulum at augue consequat augue commodo fringilla eget vitae sapien. Cras rhoncus dolor ac augue pulvinar, sit amet tempus felis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec eget massa felis. Pellentesque sodales ante in nisi mollis, at dictum orci pellentesque. Praesent in quam nulla. Sed nec ligula in augue suscipit dictum. Nullam sed risus rhoncus, dapibus metus vel, sagittis justo. Proin erat mauris, fermentum id mauris quis, ullamcorper rhoncus ligula.\n" +
                "\n" +
                "Proin posuere, lorem sed pretium tempor, risus massa iaculis dolor, ac porta erat leo eu eros. Cras vulputate ante elit, nec tempor mi rutrum vel. Nunc quis enim mattis, rhoncus augue id, eleifend velit. Quisque vehicula ante ante, ut venenatis lorem venenatis at. Morbi ut dictum dui. Ut justo augue, tristique a nisl laoreet, iaculis viverra tellus. Pellentesque ut elit non elit dictum hendrerit a sit amet ipsum. Ut non tellus sed felis iaculis accumsan vel ac lorem. Donec ac egestas est.\n" +
                "\n" +
                "Integer porta porta facilisis. Morbi eget viverra tortor. Curabitur efficitur dui accumsan tincidunt laoreet. Mauris laoreet dignissim consequat. Quisque vulputate pellentesque purus, in venenatis risus ultrices vehicula. In euismod, leo a consectetur sagittis, tortor enim faucibus justo, vel pellentesque justo massa non tortor. Nullam efficitur orci ac feugiat vehicula. Nullam mollis sit amet risus consequat feugiat. Vivamus efficitur maximus justo, non tristique magna luctus eget. Cras et odio sem. Phasellus malesuada blandit sem, eget efficitur augue ultricies vel. Nullam ornare aliquam diam ac blandit.\n" +
                "\n" +
                "Suspendisse dictum est ex, at suscipit lorem efficitur sed. Pellentesque at porta orci. Curabitur pretium leo elit, eget tincidunt leo faucibus condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse condimentum enim ut est posuere viverra. In a venenatis magna. Nullam nisi lorem, mattis ac fermentum ornare, consequat et ante. Sed tincidunt odio a turpis venenatis, eu venenatis ipsum tempor. Mauris vitae erat sit amet metus sagittis vulputate. Pellentesque auctor dolor vitae placerat finibus. Pellentesque vehicula dolor quis interdum malesuada. Aenean consequat sagittis pellentesque.\n" +
                "\n" +
                "Praesent pretium ante rutrum enim vehicula posuere. Ut facilisis porta orci, nec hendrerit enim interdum a. Donec sed purus iaculis, finibus velit euismod, tempus elit. Morbi lorem elit, convallis suscipit ipsum in, tempus mollis turpis. Nunc eget libero nec ligula finibus convallis a eu leo. Pellentesque auctor tincidunt scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc consectetur turpis quis augue rutrum, id egestas orci fringilla. Cras non lectus ligula. Integer scelerisque, purus id varius convallis, ex elit cursus neque, sed convallis mauris est ac metus. Sed consectetur pulvinar diam, sed tincidunt ante aliquam vitae.\n" +
                "\n" +
                "Quisque urna metus, euismod ut rutrum sit amet, consectetur nec tellus. Nulla tincidunt laoreet purus ac fringilla. Suspendisse eget mattis tellus. In sit amet ante ac lectus finibus aliquet. Morbi ut ultricies arcu, ut convallis dui. Ut feugiat pellentesque odio a luctus. Donec nec ullamcorper nisi, quis luctus est. Sed gravida, nulla ac molestie ultrices, diam ligula ultricies lorem, id laoreet purus ipsum eu tellus.\n" +
                "\n" +
                "Morbi ultrices nisi condimentum, vehicula lorem at, faucibus tellus. Aenean vitae metus finibus, lacinia lectus nec, dapibus ligula. Nunc feugiat quam nec ligula tincidunt semper. Ut ut elit eget nisl gravida maximus vel eget libero. Vestibulum id risus aliquam, placerat massa at, tincidunt justo. Proin imperdiet justo lorem, eu porttitor nisl gravida vel. Pellentesque in diam nibh. Vestibulum quis ante vitae orci auctor rutrum. Praesent tincidunt velit a arcu malesuada, at pretium turpis semper. Pellentesque laoreet mauris eget laoreet laoreet. Vestibulum fermentum nisl placerat sem egestas, sit amet dignissim nisi rhoncus. Curabitur lobortis turpis justo, at tempor enim scelerisque sit amet. Aenean et orci vel eros ornare semper ac imperdiet turpis. Nunc eu lacinia odio. Etiam fringilla nulla lorem, vitae luctus est posuere et. Curabitur gravida facilisis rutrum.\n" +
                "\n" +
                "Vivamus scelerisque nunc vitae aliquet eleifend. Sed quis nisl suscipit nulla cursus ullamcorper. Donec dignissim augue at elit interdum efficitur. Proin leo nibh, vestibulum cursus ligula vel, tincidunt ullamcorper quam. Phasellus rutrum purus et purus dapibus, sit amet congue ligula iaculis. Proin iaculis tincidunt neque rhoncus dignissim. Aliquam scelerisque urna fringilla purus pulvinar, vel vulputate odio bibendum. Aenean vehicula tellus non ante sollicitudin viverra. Nunc vitae massa eget diam malesuada fermentum vel et elit. Nulla a felis eget sapien ullamcorper vulputate faucibus a dolor. Praesent placerat interdum hendrerit. Praesent rhoncus velit eu libero egestas fermentum. Curabitur turpis sem, suscipit vel lorem ut, blandit faucibus sapien.\n" +
                "\n" +
                "Morbi aliquet turpis non diam tincidunt viverra. Donec a congue tortor. Nam tristique arcu interdum, elementum quam sed, aliquet quam. Morbi metus orci, dapibus eu sapien ut, sodales ornare leo. Proin quis luctus ipsum, eu auctor neque. Duis sed volutpat felis. Suspendisse arcu massa, viverra in tortor vel, pharetra suscipit sapien.\n" +
                "\n" +
                "Aenean finibus ante id dolor pellentesque imperdiet ac a nunc. In lacus metus, iaculis vitae odio non, viverra sollicitudin magna. Nullam nec accumsan diam. Integer porttitor, turpis vitae maximus aliquet, orci turpis dignissim tellus, ut imperdiet urna dolor nec odio. Nam gravida urna ac convallis interdum. Nulla venenatis eros in vulputate maximus. Morbi sagittis erat sapien, vel consectetur tellus pharetra eu.\n" +
                "\n" +
                "Fusce eu leo ut orci tristique consequat. Etiam elementum venenatis sollicitudin. Suspendisse eleifend odio sit amet urna efficitur tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sagittis pellentesque mauris, commodo imperdiet orci commodo eget. Nullam dapibus ligula ac felis dapibus consectetur. Morbi imperdiet quam neque, nec cursus orci tempor lobortis. Sed eu justo non arcu facilisis gravida ac non elit. Nulla faucibus dui porttitor laoreet efficitur. Ut suscipit rutrum interdum. Maecenas sed metus non lorem placerat scelerisque. Nunc consequat est quis auctor tincidunt. Quisque facilisis sollicitudin velit, sed luctus tellus. Sed a justo vel arcu vehicula semper.\n" +
                "\n" +
                "Ut fermentum facilisis risus ut cursus. Donec commodo finibus tincidunt. Proin eu rutrum velit. Donec quis velit ut odio sollicitudin condimentum. Pellentesque vitae maximus sapien, a ullamcorper tellus. Vivamus vehicula odio et metus dapibus, consequat tempor nisi hendrerit. Donec elit velit, feugiat eget mauris ut, iaculis volutpat dolor. Etiam et nibh tortor. Suspendisse nulla mauris, rhoncus nec efficitur at, maximus sed felis. Pellentesque mollis molestie leo, ac ultricies massa tincidunt ut. Phasellus efficitur lectus non libero tempor scelerisque. Quisque ut leo sed mi pulvinar posuere in in orci. Curabitur at venenatis eros.\n" +
                "\n" +
                "Vestibulum eu mollis ipsum, in bibendum arcu. Nunc nec interdum velit. Ut cursus venenatis nisi pellentesque fringilla. Sed semper libero et nibh fringilla, vel luctus elit porta. Ut auctor varius lacus nec eleifend. Suspendisse a dignissim tellus. Nulla aliquam nulla quis augue accumsan, ac congue urna aliquam. Morbi justo massa, finibus ut porta scelerisque, mollis tincidunt enim. Aenean pharetra, nunc vel tincidunt ullamcorper, nisl turpis pellentesque lorem, sit amet egestas purus mi at augue. Praesent at felis consectetur, iaculis ipsum id, porta nulla. Ut mollis consectetur eleifend. Ut non bibendum lorem.\n" +
                "\n" +
                "Nunc nec congue urna, vel iaculis nulla. Donec rhoncus lacinia sagittis. Vivamus in dolor congue, tincidunt justo at, vestibulum nulla. Quisque ullamcorper viverra dolor id tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lobortis faucibus sapien eget fringilla. Cras rutrum vehicula augue, sed viverra quam auctor non. Integer euismod, felis nec elementum elementum, odio diam eleifend risus, vitae venenatis nulla metus at lacus. Fusce non purus auctor, commodo nulla vel, volutpat ipsum. Donec dictum vel risus quis mattis. Nulla facilisi. Curabitur sed ipsum a erat eleifend maximus eu ut est. Mauris risus tellus, luctus sed interdum a, scelerisque eu mauris.\n" +
                "\n" +
                "Quisque neque mauris, vulputate eget tortor nec, faucibus molestie mauris. In porta augue sed risus ultricies, quis interdum augue suscipit. Aliquam porttitor sapien neque, non consequat diam blandit nec. Ut nec nulla eget nisl eleifend condimentum. Aenean mi nisl, consectetur a vestibulum ut, sagittis id arcu. Praesent interdum sed eros sed laoreet. Donec sodales rutrum sapien, at convallis ante dignissim at. Pellentesque et laoreet urna. Praesent at massa eget nulla dignissim faucibus ac at urna. Aliquam vel est sed ex tincidunt venenatis at sed augue. Morbi eu porttitor dolor, vitae tristique nulla. Nulla sit amet placerat felis, in dictum arcu.\n" +
                "\n" +
                "Integer accumsan volutpat auctor. Ut fringilla mattis fringilla. Nullam vitae sagittis dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean condimentum lacinia cursus. Nam nulla ante, tristique in orci in, faucibus auctor arcu. Etiam arcu lectus, scelerisque at turpis non, condimentum dignissim neque.\n" +
                "\n" +
                "Quisque tempor leo quis dolor sodales aliquet. Aenean non lacus in massa egestas aliquam. Cras rhoncus ultrices augue, nec pellentesque leo bibendum efficitur. Aenean vitae odio ornare, egestas nisi eget, pretium velit. Aliquam vel tempor leo. Suspendisse rhoncus porta orci elementum vulputate. Donec laoreet ultrices elementum. Phasellus ac nulla odio. Vivamus tellus tortor, ornare ut risus sit amet, efficitur finibus massa. Etiam vel tortor ornare, volutpat sapien maximus, suscipit libero. Nulla rhoncus nunc et nulla elementum, at tempor purus auctor. Suspendisse nec tempus arcu, vel sagittis urna. Nunc in massa tristique orci scelerisque pulvinar. Aliquam sit amet gravida elit, ut vulputate sem.\n" +
                "\n" +
                "Nam rhoncus ante sit amet orci interdum, vel rhoncus sem pretium. In lectus augue, varius sed iaculis egestas, posuere vel arcu. Donec nec facilisis arcu. Donec ullamcorper lacinia pharetra. Sed vitae suscipit dui. Proin vulputate pretium ex, vitae feugiat erat placerat ac. Quisque eget urna eu ex ornare hendrerit. Suspendisse turpis dolor, mollis in leo et, porttitor lobortis mi. Nunc dictum diam eu arcu sodales dictum.\n" +
                "\n" +
                "Aliquam erat volutpat. Praesent faucibus mauris eu tellus vulputate, vitae condimentum sem feugiat. Ut sit amet mattis felis. Curabitur at erat in metus volutpat egestas at vitae tortor. Donec id sem tempus, tempus ipsum sit amet, mollis erat. Donec non velit non velit blandit elementum. In volutpat placerat enim, ut scelerisque augue malesuada iaculis.\n" +
                "\n" +
                "Donec eu ligula ante. Mauris eros mauris, eleifend nec augue elementum, porta vulputate magna. Mauris mattis ex ligula, ac mollis elit posuere semper. In lacinia sapien eu arcu ornare, eget bibendum nulla egestas. Quisque id imperdiet tellus. Aenean lacus nibh, varius non viverra sit amet, faucibus ac mi. Nullam mollis ex turpis, et vehicula metus posuere vitae. Etiam dictum nec libero placerat mollis. Phasellus tristique orci sit amet bibendum commodo. Aenean a purus id turpis vulputate mollis. Sed massa velit, condimentum nec consequat ac, vehicula venenatis neque. Donec finibus euismod leo nec aliquam. Vestibulum a venenatis mauris, volutpat egestas risus. Mauris dictum aliquet urna, sed hendrerit turpis. Pellentesque eleifend velit ut metus gravida, a pellentesque nisl lacinia. Sed tincidunt ipsum ligula, non fringilla arcu euismod vel.\n" +
                "\n" +
                "Aliquam tincidunt auctor egestas. Vestibulum pharetra consequat lobortis. Pellentesque eu urna vel diam euismod venenatis. Suspendisse placerat eu justo eu vulputate. Etiam vulputate justo eget tellus ultrices maximus. Aliquam ac porta lectus, sed pellentesque metus. Sed tincidunt sollicitudin elit, vitae iaculis eros porttitor sed.\n" +
                "\n" +
                "Suspendisse cursus arcu nec mi semper tempus. Morbi tincidunt at arcu sit amet accumsan. Quisque consectetur metus a tincidunt efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut urna lectus. Nam est mi, mattis vel iaculis ut, venenatis sed turpis. In luctus erat ultricies augue eleifend ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In eu gravida nisl. Integer convallis diam aliquam nunc bibendum, et tristique lorem pharetra. Nullam sed arcu eleifend lectus facilisis accumsan. Maecenas lobortis mi felis, vel fermentum arcu vestibulum sed. Nulla dignissim libero eu eros rutrum ultrices.\n" +
                "\n" +
                "Duis dignissim, purus id cursus aliquet, orci ligula efficitur mi, nec aliquam sem diam vel velit. In hac habitasse platea dictumst. Cras elementum vehicula nisi, in mollis diam faucibus quis. Cras quis magna a dolor tempor interdum non eget nisl. Sed tempor eleifend sapien vitae ornare. Nunc efficitur a ante et feugiat. Quisque orci justo, ullamcorper in ex at, aliquam dignissim elit. Praesent accumsan, neque quis fermentum malesuada, odio dui posuere libero, eleifend faucibus ipsum sapien at magna. In hac habitasse platea dictumst. Vivamus feugiat, justo pretium vulputate rhoncus, quam urna rhoncus est, ac posuere massa ex et enim. Sed blandit nunc vel maximus aliquet. Maecenas imperdiet diam quis pulvinar tincidunt. Cras mattis aliquet dapibus. Phasellus at laoreet ipsum, sed viverra magna. Praesent interdum urna quis risus gravida dictum ut eget orci. Aliquam risus sapien, venenatis at malesuada auctor, ornare sit amet nulla.\n" +
                "\n" +
                "Nullam vel mi ante. Donec ultricies ac magna et elementum. Ut bibendum elit a neque rhoncus commodo. Sed et turpis sit amet ligula sodales consectetur id quis sem. Aenean ex enim, porta eget ultricies at, vulputate quis nibh. Duis malesuada diam sed ultrices sollicitudin. Vivamus id ornare lacus. Pellentesque augue nulla, efficitur facilisis tortor dapibus, accumsan efficitur nibh. Duis ornare auctor nunc, et interdum ex ornare id. Morbi et pellentesque sapien, et porta metus. Vivamus dapibus arcu arcu, ac maximus urna facilisis luctus. Aenean sed gravida eros. Sed ornare diam et ex sagittis, ornare bibendum ante tempor. Suspendisse libero sem, eleifend vel augue sit amet, laoreet dignissim lectus.\n" +
                "\n" +
                "Aliquam vestibulum tellus augue, eget consectetur lorem tristique sed. Donec id metus quis ligula vulputate faucibus. Praesent risus elit, consequat ut sagittis eu, tincidunt sed eros. Aenean faucibus massa ac ex scelerisque, quis ultricies justo scelerisque. Cras id enim quam. Suspendisse hendrerit sagittis aliquam. Vestibulum faucibus, odio in fermentum malesuada, orci magna viverra orci, eu ultrices tellus ante ac ipsum. Sed ac dolor faucibus, maximus purus non, ultrices magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec non purus non leo fermentum lacinia ut quis augue. Aenean viverra porttitor purus id varius.\n" +
                "\n" +
                "Nunc auctor tempus ante, maximus vulputate justo semper vel. Aliquam molestie odio nec odio aliquet aliquam. Aenean mollis magna odio, in condimentum dui elementum eget. In at vehicula mi. Vivamus sed tortor cursus magna suscipit rhoncus commodo quis ex. Aliquam sed est diam. Vestibulum suscipit porta est, quis pretium felis ullamcorper aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vehicula tincidunt ligula, eget iaculis quam consectetur ac. Integer vel orci nisl. Praesent faucibus eget quam ac euismod. Sed nisl felis, malesuada id nisi nec, hendrerit dignissim nulla. Etiam purus ligula, feugiat lobortis urna cursus, tincidunt euismod massa.\n" +
                "\n" +
                "Nam porta nulla et magna finibus porttitor. Etiam in urna dolor. Curabitur ac nisi eleifend ex pulvinar vulputate. Proin id mauris a mauris feugiat interdum. Cras vehicula ex eget elit facilisis commodo. Pellentesque dapibus imperdiet est ornare semper. Maecenas purus nisl, pretium ut dui in, euismod dapibus tortor. Nunc gravida sem quam, quis bibendum odio tincidunt a. Sed tristique massa eu auctor pulvinar. Sed et semper turpis. Quisque porttitor venenatis iaculis.\n" +
                "\n" +
                "Nam sed porttitor sem, eu viverra arcu. Nam non fringilla mauris. Vestibulum varius felis quis felis vulputate consequat. Vivamus dictum egestas dolor, nec vehicula mi cursus lacinia. Duis vehicula interdum sollicitudin. Vestibulum sit amet egestas arcu. Aliquam ac sem nibh.\n" +
                "\n" +
                "Phasellus cursus lorem nec urna sollicitudin, non fringilla dolor suscipit. Morbi risus lacus, facilisis vel mauris sit amet, blandit laoreet lacus. In hac habitasse platea dictumst. Donec ut lacus elit. Sed at dapibus dui, in facilisis lectus. Aliquam ac maximus lacus. Morbi a fringilla odio. Curabitur vel diam non est malesuada mollis eu quis enim. Pellentesque erat tellus, lacinia eu sodales ut, lobortis vitae massa. Aliquam sit amet velit felis. Quisque posuere sem in augue volutpat, in scelerisque tortor lacinia. Praesent sed tincidunt erat, vel feugiat eros.\n" +
                "\n" +
                "Morbi tincidunt enim sit amet faucibus consequat. Integer euismod, erat id cursus porta, odio tellus vehicula risus, non lobortis dolor nunc in ante. Maecenas et tortor dignissim, ultrices odio a, porta libero. Proin eget tortor nibh. Nullam ac dapibus lacus, eget tincidunt felis. Vestibulum nisl urna, volutpat in interdum vel, pulvinar quis nulla. In tristique at nisl et rhoncus. Nullam pulvinar arcu sapien. Aliquam in lorem vitae arcu lacinia cursus. Etiam convallis, lectus et tristique ullamcorper, elit tortor vestibulum diam, convallis iaculis massa lorem et ligula.\n" +
                "\n" +
                "Suspendisse vel dolor eros. Suspendisse auctor lacinia nibh, vel finibus velit. Aliquam commodo sodales leo, sit amet fringilla eros convallis et. Fusce vestibulum felis sed accumsan interdum. Vivamus placerat tincidunt mollis. Cras finibus nunc dictum quam eleifend elementum. Donec ornare mauris vitae justo malesuada, interdum posuere justo varius. Aliquam nisi est, rhoncus sed diam sed, euismod bibendum diam. Sed quis sodales ante, nec laoreet eros. Proin libero massa, aliquet sit amet mauris sed, viverra pharetra ex.\n" +
                "\n" +
                "Fusce eu pellentesque risus. Suspendisse nec metus hendrerit, semper purus dictum, accumsan sapien. Nam vel dui lacus. Proin ornare eros et lacus fringilla tincidunt. Ut iaculis interdum ultrices. Mauris suscipit, nibh sit amet tincidunt varius, felis quam facilisis tortor, eget lobortis felis lacus quis nunc. Suspendisse potenti. Donec in elit vel lorem consectetur blandit. Aenean a ligula at leo congue cursus sit amet eget orci.\n" +
                "\n" +
                "Integer suscipit tincidunt pellentesque. Nulla facilisi. Vivamus tempor eget mauris eget luctus. Sed commodo tortor vel diam sollicitudin vehicula. Donec eu pretium diam, eget pretium lacus. Etiam sed lacus laoreet, viverra tortor ac, maximus sem. Sed aliquam, lorem sed laoreet tincidunt, sem nisi scelerisque velit, sit amet laoreet leo leo in justo. Duis iaculis vitae nulla ut fringilla. Ut quam augue, efficitur in magna vel, rhoncus aliquet dolor. Pellentesque aliquam magna eu elit elementum tincidunt. Suspendisse molestie congue diam quis faucibus. Donec ac lacinia nisi, eu ornare orci. Aenean eros eros, ullamcorper nec lacinia in, tincidunt a arcu. Sed dignissim risus in efficitur mattis.\n" +
                "\n" +
                "Pellentesque arcu quam, ultrices luctus condimentum eget, porta in lacus. Vestibulum ex ex, sodales at nulla non, tempus pretium sapien. Vivamus nunc lectus, egestas eu ultrices non, volutpat non dolor. Sed at nisi et arcu pharetra viverra et at dui. Fusce lacus lacus, egestas id porttitor non, auctor varius tortor. Quisque gravida nisi enim, ornare scelerisque purus venenatis dapibus. Nunc venenatis tellus ac risus efficitur tempus non ut turpis. Quisque non turpis et erat tempus porta. Cras sem erat, tincidunt ac nulla a, posuere faucibus enim. Vestibulum vitae ante placerat, auctor erat nec, tincidunt mauris. Ut sit amet aliquam nulla. Donec pellentesque leo sed fringilla consectetur. In nec rutrum nisl. Fusce varius ligula nec rutrum maximus.\n" +
                "\n" +
                "Phasellus eleifend efficitur eleifend. Cras dignissim nibh felis, eu elementum ipsum scelerisque vitae. Morbi pellentesque nunc odio, in commodo purus lobortis eu. Proin malesuada dignissim quam, at tincidunt ligula iaculis et. Nullam lorem dolor, fringilla vitae vehicula ultricies, condimentum id augue. Mauris non pharetra felis, eget ultricies metus. Cras fermentum semper augue vitae dignissim. Sed tincidunt suscipit finibus. Nulla at leo eu lectus euismod consectetur. Duis eleifend non felis ac congue. Proin maximus, dolor ut porttitor pretium, quam sapien maximus lectus, nec mattis turpis mauris vitae dui. Etiam eu ligula nec metus elementum condimentum eget congue quam. Proin quis magna eget dolor accumsan vulputate quis id magna.\n" +
                "\n" +
                "Sed rhoncus ligula a efficitur imperdiet. Cras porttitor nunc sed molestie sodales. Donec ornare purus nisi, id consequat erat malesuada ac. Etiam vitae egestas leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque luctus nisl quis convallis tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae facilisis lacus, vitae tincidunt neque. Cras vel dolor eget nulla ultricies congue. Nunc rhoncus dui arcu, sit amet ornare orci porta vitae. Nunc at massa at nunc congue vulputate.\n" +
                "\n" +
                "Proin vel eleifend magna, ut eleifend nulla. Ut lacinia tempor eleifend. Sed pharetra tellus eu mauris lacinia gravida eu ut libero. Donec elementum accumsan justo ut convallis. Morbi elementum suscipit egestas. Donec rutrum consequat ullamcorper. Proin porttitor magna in convallis tincidunt. Nulla facilisi. Mauris id elementum nisl. Etiam in blandit ex, eu porttitor turpis. Praesent maximus magna enim, et lacinia dolor egestas sit amet. Nullam lectus enim, iaculis suscipit suscipit sit amet, pharetra vitae mauris.\n" +
                "\n" +
                "Nunc ut erat ipsum. Proin dignissim justo et sem fermentum lacinia. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin purus eu libero vestibulum, ut efficitur erat vehicula. Ut malesuada libero dui, at pretium sem aliquam vitae. Pellentesque a sodales odio. Nam a consectetur tortor, sed pharetra tortor. Fusce egestas leo nec tellus finibus efficitur. Ut purus libero, scelerisque vehicula vulputate posuere, semper quis leo. Sed quis posuere lorem. Curabitur eu dictum neque. Phasellus at nunc dolor. In semper pharetra ex at tempor.\n" +
                "\n" +
                "Sed pulvinar imperdiet tristique. Nulla facilisi. Nulla ac sapien ex. Sed sollicitudin vitae felis nec condimentum. Suspendisse vel malesuada tortor. Donec sagittis odio in dignissim rhoncus. Morbi pretium efficitur erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris laoreet, quam vel tempor condimentum, odio lectus volutpat erat, sit amet vulputate est ipsum et leo. Suspendisse urna nibh, facilisis in sodales ac, auctor ut lacus. Aenean convallis arcu quis pharetra eleifend.\n" +
                "\n" +
                "Vestibulum elementum pharetra augue, id finibus massa tempus id. Sed et iaculis sem. Nunc quis vehicula nisi. Praesent eleifend sagittis velit. Proin lacinia leo sed libero semper, eget ultricies lectus convallis. Nulla semper vestibulum turpis sit amet auctor. Morbi luctus tellus et urna fermentum, ac varius nisl maximus. Ut efficitur arcu nunc, vitae maximus elit laoreet eget. Donec gravida leo at metus fringilla, ac suscipit purus egestas. Sed vel efficitur mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam egestas eleifend ipsum, ut finibus turpis dignissim non. Suspendisse potenti. Phasellus a eros est.\n" +
                "\n" +
                "Phasellus vehicula ex sed sem luctus gravida. Nunc suscipit magna massa, non fringilla orci fringilla eu. Aliquam vitae venenatis ante, sed egestas enim. Sed congue velit eget dictum porta. Duis auctor fringilla turpis vitae dignissim. Morbi quis mauris viverra est vehicula volutpat ut et odio. Aenean accumsan sem sit amet elit dignissim varius. Vivamus sed lectus accumsan, molestie ligula ac, consectetur felis. Nunc at urna eu dui consectetur volutpat quis eget risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur viverra interdum diam ac elementum.\n" +
                "\n" +
                "Fusce nisl elit, facilisis at ullamcorper a, vulputate quis magna. Nullam rutrum dui at orci laoreet vehicula. Maecenas molestie ultricies elit sit amet accumsan. Quisque ornare tempus posuere. Vivamus mauris odio, fermentum vel sem eu, posuere aliquam neque. Pellentesque commodo ipsum condimentum eros blandit euismod. Suspendisse potenti. Maecenas lacinia ac lorem eu ultricies. Suspendisse pharetra massa quis semper bibendum.\n" +
                "\n" +
                "Mauris dapibus magna sit amet malesuada ullamcorper. Aenean lorem ante, elementum quis ex in, tincidunt fringilla quam. Pellentesque condimentum pulvinar auctor. In risus risus, tempus quis elit sed, semper pharetra elit. Praesent molestie aliquet accumsan. Integer non purus a ipsum luctus mollis a sed quam. Quisque enim risus, vestibulum vitae finibus et, euismod ultricies libero. Donec ultricies bibendum semper. Nulla dolor leo, facilisis sed tempus in, congue sed metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur lorem turpis, pretium eu efficitur at, tempor eget turpis. Donec dapibus nunc nec enim tincidunt vehicula. Aliquam et dolor tempor, laoreet tellus a, tristique elit. Nam at ligula pretium, aliquet orci malesuada, accumsan sem. Fusce a sagittis sapien. Ut sagittis condimentum sem, vitae porta mauris convallis eu.\n" +
                "\n" +
                "Duis facilisis lectus vitae massa blandit, nec elementum ante bibendum. Duis blandit ex lorem, non semper orci tristique vitae. Curabitur sollicitudin felis in porttitor tempus. Praesent mattis eros placerat magna laoreet, sit amet convallis sem mollis. Vivamus sapien ipsum, consectetur et orci ut, venenatis fermentum arcu. Morbi efficitur luctus mi quis elementum. Proin et consequat eros, eget luctus mauris. Maecenas ligula lacus, elementum sit amet ornare eget, iaculis in enim. Nullam nec ex id magna rhoncus convallis in molestie nisl. Integer in nunc velit. Cras sit amet ipsum non justo imperdiet pulvinar et id neque. Maecenas vel ullamcorper mauris, eu egestas metus. Curabitur et venenatis justo, eu sollicitudin quam.\n" +
                "\n" +
                "Nam magna magna, malesuada nec risus sit amet, aliquam fermentum sapien. Donec dictum imperdiet nisl a cursus. Fusce semper gravida libero id malesuada. Proin ac facilisis justo. Cras interdum gravida iaculis. Integer congue, nunc vel luctus sollicitudin, elit est porta erat, sed maximus metus neque et odio. Duis dictum suscipit neque, eget condimentum leo venenatis vitae. Maecenas quis porta justo. Donec urna nulla, ornare bibendum lectus et, aliquet maximus enim. Morbi et urna odio. Praesent vitae ultricies est, ac tincidunt felis. Morbi porta elit neque, quis sollicitudin dolor molestie in.\n" +
                "\n" +
                "Sed posuere dapibus lobortis. Maecenas malesuada elit in lacus efficitur, sit amet malesuada nisi blandit. Suspendisse ullamcorper viverra dui vitae porta. Nulla fermentum ultricies ligula id cursus. In et ullamcorper lacus. Phasellus et neque nunc. Proin felis eros, lobortis quis mollis eu, laoreet rutrum nulla.\n" +
                "\n" +
                "Morbi sed magna purus. Curabitur non ante orci. Suspendisse vel malesuada nisi, at tempor enim. Sed scelerisque ultricies est id laoreet. Ut pharetra turpis gravida ipsum posuere, eget fringilla quam finibus. Etiam vitae risus rhoncus, luctus ligula et, pellentesque nibh. Curabitur vehicula, orci at lobortis efficitur, erat libero cursus ipsum, eget ullamcorper felis sapien sit amet tortor. Vestibulum mauris arcu, semper eu tellus vel, fermentum pulvinar dolor. Integer ut ligula sollicitudin, viverra purus at, scelerisque libero. Duis sagittis gravida augue sed scelerisque. Maecenas odio ipsum, facilisis sit amet augue id, facilisis bibendum urna. Donec ullamcorper volutpat sollicitudin. Nullam venenatis purus et lacinia imperdiet. Pellentesque tempor felis et lacus vehicula accumsan. Fusce sit amet fermentum ante, non scelerisque enim. Donec rutrum, dui vel eleifend viverra, ante dolor iaculis enim, eget ultricies odio erat et nisi.\n" +
                "\n" +
                "Curabitur eget odio sed nulla aliquam sodales et eu felis. Donec ex massa, tristique sed aliquet in, imperdiet at nulla. Donec pellentesque tellus vitae metus iaculis pulvinar. Vestibulum nulla felis, auctor sed mauris sed, tempus placerat turpis. Ut pellentesque nulla eu leo placerat lacinia. Mauris congue nisi nibh, id accumsan sem vehicula vel. Curabitur maximus sem in iaculis mattis.\n" +
                "\n" +
                "Nulla viverra est eget purus pellentesque sollicitudin. Nunc risus quam, posuere id nibh eget, placerat semper velit. Curabitur quis leo aliquam, molestie risus vel, facilisis ante. Aenean eros magna, elementum non nisl vitae, placerat congue velit. Mauris a volutpat elit. Nulla luctus turpis vel tempus convallis. Nam non eros eget elit eleifend porttitor et eget leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur viverra vel magna a venenatis. Praesent porttitor magna id consectetur sollicitudin. Aliquam porttitor dui nec vehicula sodales.\n" +
                "\n" +
                "Curabitur pellentesque eu quam sit amet dictum. Donec molestie tincidunt dui, ut pellentesque leo varius vel. In at mauris quis augue interdum tempus. Proin pharetra turpis metus, in ullamcorper ex pharetra ac. Aenean lobortis ligula dignissim ex volutpat varius. Phasellus eros justo, blandit a gravida malesuada, congue eget urna. Pellentesque malesuada efficitur ligula, ut convallis libero convallis sit amet. Morbi sed mauris et lectus tincidunt tincidunt. Aenean dapibus gravida libero eu viverra.\n" +
                "\n" +
                "Vivamus fermentum massa nec dignissim viverra. Nullam fringilla metus vel metus commodo accumsan sit amet at dui. Proin ultrices mi elementum placerat semper. Cras quis aliquam turpis, eu commodo eros. Aliquam suscipit urna ut tortor suscipit, ac eleifend tellus placerat. Vivamus mi turpis, cursus quis purus id, maximus luctus metus. Morbi ipsum ante, imperdiet at lorem id, rhoncus accumsan massa. Donec interdum vitae est vitae consequat. Suspendisse potenti.\n" +
                "\n" +
                "Donec ornare purus vitae velit blandit vehicula. In sit amet lectus tincidunt quam hendrerit euismod nec in tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in aliquam leo, non consectetur mi. In vitae laoreet sapien. Nam lobortis, turpis vel elementum facilisis, nunc mauris sagittis eros, vel fermentum ante elit vel odio. Phasellus vehicula urna sed diam vulputate, eu lobortis sem dignissim. Vestibulum at ipsum lacus.\n" +
                "\n" +
                "Curabitur mi tortor, ultrices eu venenatis at, placerat vel erat. Duis ullamcorper feugiat diam, at facilisis lorem eleifend at. Pellentesque ut iaculis quam, nec ullamcorper metus. Morbi quam nulla, accumsan iaculis ligula viverra, dignissim ornare velit. Sed tempor molestie ex vitae ultrices. Etiam vitae bibendum dui. Vivamus sodales elementum diam, a viverra dui varius id. Donec ullamcorper, mauris nec efficitur tristique, lectus tortor semper lacus, et porttitor elit ex a massa.\n" +
                "\n" +
                "Mauris dignissim tortor velit, sit amet maximus dolor tincidunt vitae. Nam eu sem laoreet, mollis odio a, ultrices elit. Donec lacinia dolor congue, sollicitudin lacus id, luctus metus. Sed blandit imperdiet lacus, faucibus aliquam purus. Sed pulvinar ullamcorper arcu at lacinia. Proin sodales hendrerit urna a tristique. Fusce non justo eu urna accumsan pellentesque sit amet vel nisi. Pellentesque ante diam, rhoncus ut blandit quis, vulputate sit amet leo.\n" +
                "\n" +
                "Aliquam at lectus sit amet lectus luctus venenatis eget pulvinar risus. Cras a magna consectetur, porta sapien in, ornare diam. In consequat id velit eget vulputate. Phasellus commodo eu lorem vel aliquet. Aenean nec sollicitudin lorem. Sed imperdiet nec sapien nec vulputate. Nullam orci lectus, imperdiet volutpat ullamcorper non, dapibus quis dolor. Aenean justo ipsum, scelerisque id tortor eget, malesuada euismod sapien. Curabitur blandit ligula augue, vel rutrum nunc facilisis ac. Duis nec urna in ex consectetur placerat in ac turpis. Donec efficitur bibendum ante, eu ullamcorper nibh elementum id. Curabitur egestas lacinia sem sit amet ultrices. Fusce facilisis vehicula hendrerit.\n" +
                "\n" +
                "Proin hendrerit dui in vestibulum pharetra. Integer eget faucibus tortor, mollis gravida nunc. Proin laoreet augue purus, et blandit lectus pulvinar at. Donec malesuada porta tristique. Suspendisse pharetra malesuada erat eget vestibulum. Nam vel diam convallis, semper lacus dictum, placerat orci. Proin congue, est ut efficitur pretium, ex leo aliquam odio, eu tempor mauris ante non orci. Aenean bibendum varius dolor, id iaculis purus vehicula ac. Duis varius orci id tempor elementum. Nam eu accumsan arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc eu augue ornare, placerat neque ac, cursus dui. Aliquam et ante vitae urna venenatis mollis. Suspendisse semper mattis est vel laoreet.\n" +
                "\n" +
                "Phasellus porttitor ipsum ut magna gravida, quis fermentum nisi rhoncus. Vivamus vitae nibh enim. Proin nec arcu porttitor, sodales ante quis, auctor dolor. Quisque elementum hendrerit sapien, a varius turpis dignissim ac. Ut convallis quam eleifend diam facilisis placerat. Morbi mollis tortor diam, vitae mollis tellus bibendum vel. Nam sed aliquam neque, porttitor fermentum nisl. Donec dignissim metus non mi euismod commodo. Mauris scelerisque tortor eget tellus egestas pellentesque. Fusce et massa arcu. Sed lobortis lobortis mollis. Sed hendrerit, dolor in ultrices condimentum, augue dui laoreet massa, a varius mi magna ac ipsum.\n" +
                "\n" +
                "Aliquam erat volutpat. Phasellus scelerisque ultrices ligula eget viverra. Aenean eget sapien at nisi condimentum feugiat. Donec eget nibh ultricies, ultrices velit consequat, malesuada eros. Quisque eu diam magna. Curabitur velit eros, gravida at rutrum vitae, scelerisque sit amet nisi. Nunc cursus sem sit amet sollicitudin fringilla. Praesent pretium sodales porttitor. Nam non ex et justo tincidunt dignissim. Morbi non est ornare metus viverra sodales. Sed consectetur accumsan imperdiet.\n" +
                "\n" +
                "Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vel mollis diam, in cursus ante. Aliquam consequat tincidunt velit a fermentum. In hac habitasse platea dictumst. Nulla vestibulum sollicitudin nisl. Etiam a nisi sed urna aliquam sollicitudin non varius nibh. Quisque ultricies placerat libero, ullamcorper dignissim est tristique at. Cras vulputate ornare blandit. Ut non metus sollicitudin, sollicitudin justo eu, bibendum lacus. In aliquam tellus ut efficitur vulputate. Nam consectetur nisl non efficitur sagittis.\n" +
                "\n" +
                "Sed gravida enim lorem, id mollis enim ultrices vel. Nam et neque quis ante tempor fringilla. Fusce non molestie nulla, non vulputate arcu. Sed quis lorem in ante pulvinar pellentesque a ut neque. Etiam malesuada sodales elementum. Integer id tempus augue, vitae suscipit nunc. Duis nec mattis ex, et tristique tortor. In non erat nisl. Mauris interdum sed leo vitae consequat. Vivamus cursus quam id cursus consequat. Proin ipsum dui, lobortis nec justo ac, pulvinar rhoncus turpis.\n" +
                "\n" +
                "Suspendisse porttitor efficitur sagittis. Fusce sagittis risus vel quam efficitur, dapibus finibus justo rhoncus. Morbi sit amet semper justo, in laoreet arcu. Suspendisse consectetur nulla at quam efficitur laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae turpis eget arcu varius tristique. Aenean dignissim, ligula eget accumsan tristique, arcu tellus malesuada massa, a vestibulum purus tortor quis nisi. Aliquam suscipit sagittis venenatis.\n" +
                "\n" +
                "Duis viverra ultricies velit, sed euismod est consequat eget. Phasellus ornare felis eget leo efficitur, sit amet aliquet dolor tristique. Nunc scelerisque eget nibh at pharetra. Aliquam erat volutpat. Sed aliquam quis magna sit amet fermentum. Suspendisse potenti. Nam congue lorem eget orci rhoncus, ac tempor urna feugiat.\n" +
                "\n" +
                "In id leo dapibus risus aliquam fermentum dignissim non sem. Proin sit amet viverra orci, eget vehicula ipsum. Aliquam efficitur nec nibh in fermentum. Pellentesque non dui massa. Phasellus a est eu libero pulvinar maximus a ac tortor. Nulla pretium porttitor nisi, in tristique odio venenatis sed. Pellentesque nec tincidunt lorem.\n" +
                "\n" +
                "Donec blandit risus eu consectetur venenatis. Sed id nisl interdum, suscipit odio in, sollicitudin nisl. Vestibulum sed odio rhoncus, semper ante a, malesuada arcu. Suspendisse rhoncus tortor eu ante egestas efficitur vitae a lacus. Quisque sit amet posuere ipsum. Etiam sodales, lacus id finibus eleifend, elit justo gravida dui, in volutpat nibh tellus non felis. Fusce pulvinar feugiat ultrices. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin suscipit nunc ut justo volutpat ultricies. Curabitur volutpat risus sem, mollis consequat est iaculis eleifend. Donec dapibus convallis venenatis. Sed id nisl a lectus molestie fermentum eget nec tellus. Sed convallis rhoncus nisi id bibendum.\n" +
                "\n" +
                "Sed mi enim, finibus non sem ac, semper semper felis. Cras auctor sapien placerat mi laoreet malesuada. Sed lacinia sollicitudin pulvinar. Suspendisse ut varius libero. Duis porttitor leo magna, non sodales orci ultrices sed. Sed leo purus, ullamcorper dignissim ante semper, tempus tincidunt leo. Maecenas ligula lectus, eleifend vel sodales tempus, eleifend quis dui. In porta tortor lacinia sodales vestibulum.\n" +
                "\n" +
                "Nullam massa augue, vulputate ac aliquam in, porta a erat. In vel quam sem. Phasellus eros nisl, sollicitudin non congue at, facilisis a orci. Etiam non porttitor nibh, sed varius odio. Pellentesque nisl odio, porta eget sollicitudin nec, venenatis nec massa. Duis efficitur pharetra ex, vel viverra nisi pulvinar non. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Mauris cursus turpis augue, tempus dignissim velit eleifend et. Nam dolor ante, scelerisque at eros id, mollis viverra lacus. Nulla eleifend vehicula ligula. Sed gravida convallis ipsum at cursus.\n" +
                "\n" +
                "Suspendisse potenti. Vestibulum imperdiet turpis sem, quis vestibulum ligula sagittis vel. Phasellus dapibus tincidunt rutrum. Sed condimentum rutrum leo a pharetra. Curabitur non tincidunt augue. Curabitur vitae mi vulputate, auctor augue quis, mollis arcu. Donec sit amet tempor turpis, eu laoreet nisi. Praesent sollicitudin ex sit amet quam ultrices, non dignissim lectus varius. Donec eu neque diam. Nullam dictum nulla sed lacus lacinia, ut malesuada mauris placerat. Morbi a tristique dui. Donec sit amet dictum enim. Donec commodo elit dui, in vulputate sem viverra ac. Duis velit elit, porta sit amet pretium nec, tempus sed neque. Ut orci nibh, sodales et dui at, auctor placerat nisi. Quisque fermentum fermentum egestas.\n" +
                "\n" +
                "Fusce viverra interdum mattis. Donec aliquet vehicula lorem, id scelerisque enim elementum eget. Nunc velit turpis, gravida eget justo scelerisque, tincidunt imperdiet mauris. Vestibulum suscipit molestie sem, ac faucibus tellus ultricies et. Nullam vestibulum felis quis mauris sodales, ut ullamcorper mi luctus. Sed et sem elit. Praesent a nisi vitae metus sollicitudin ornare eu id massa. Etiam nunc dui, scelerisque ac lectus sit amet, ullamcorper elementum leo. Maecenas bibendum justo at lectus auctor, ac tincidunt sapien vehicula. Sed fermentum porttitor lacus et fermentum. Pellentesque rutrum convallis metus ac semper. Aenean eget porta nunc. Nam dolor augue, vehicula non tortor nec, venenatis lobortis ante. Aliquam lectus nisi, tristique a posuere laoreet, semper eget ipsum. Suspendisse aliquam, enim quis pretium bibendum, justo magna sollicitudin ante, quis dapibus turpis neque at erat.\n" +
                "\n" +
                "Vestibulum sit amet sapien quis nulla vulputate eleifend. Pellentesque egestas massa tempus massa molestie, eu vehicula justo auctor. Fusce a massa non ligula semper hendrerit. Sed mauris diam, ornare sed erat eget, semper condimentum diam. Donec pharetra dolor eget condimentum mattis. Duis id nisl neque. Nam posuere, eros at sodales iaculis, arcu odio varius urna, at accumsan sem velit ultrices leo. Etiam in lacus massa. Vivamus sed aliquam orci.\n" +
                "\n" +
                "Etiam bibendum urna sed risus accumsan, eu scelerisque arcu placerat. Aliquam tellus urna, eleifend ac placerat sed, vulputate id orci. Nulla semper enim ipsum, vitae facilisis mauris porta at. Nunc dictum tellus ut augue dapibus consequat. Aliquam quis egestas magna. Morbi tempor magna ac sapien sollicitudin, vitae accumsan mauris efficitur. Integer vel justo mi. Sed cursus blandit tempus. Quisque ut interdum est, eu auctor velit. Proin quis dolor egestas, blandit tortor nec, hendrerit lacus. Fusce in vulputate odio. Phasellus sagittis dui velit, quis venenatis eros laoreet vitae. Curabitur aliquam interdum cursus. Etiam at quam at lorem convallis accumsan sit amet nec metus. Integer nec laoreet quam.\n" +
                "\n" +
                "Duis vel ligula vel lectus molestie maximus efficitur in quam. Aenean tempus semper interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris vitae mauris semper, aliquet erat nec, fringilla est. Duis in ullamcorper odio, eget eleifend nisi. Nam consequat ante dolor. Mauris ultrices placerat enim ut blandit. Morbi lobortis magna eget facilisis eleifend. Etiam maximus odio nibh, id sodales neque aliquam ut. Vivamus vitae nibh nisi. Aenean maximus libero nibh, quis accumsan neque lobortis posuere. Nulla tristique libero ut convallis euismod. Nulla facilisi. Donec non consectetur diam. Vivamus congue ex semper nunc venenatis, at tempor risus commodo.\n" +
                "\n" +
                "Fusce ac pharetra lectus. Curabitur scelerisque risus ac lacus congue, sed laoreet ligula tempus. Vivamus rutrum eu mauris sed tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean vel rhoncus dui, eu ornare turpis. Maecenas nec eros ullamcorper, blandit erat eget, gravida metus. Phasellus tristique, ante ut vehicula mollis, lorem magna molestie magna, vel finibus ipsum magna in enim. Cras consequat condimentum libero at iaculis. Sed pharetra quam vitae tellus accumsan, sit amet blandit mauris mollis. Vestibulum aliquet, augue vitae aliquet volutpat, ligula justo condimentum felis, quis faucibus erat nibh placerat nisl. Cras elementum orci justo, nec sollicitudin turpis tempor id. Integer mollis semper finibus. Sed ultricies gravida justo vel pretium. Nulla facilisi. Donec scelerisque metus sed augue posuere, quis faucibus elit bibendum.\n" +
                "\n" +
                "Ut bibendum lorem id dignissim iaculis. Nullam sollicitudin, orci id fringilla rhoncus, nibh urna vulputate justo, eget gravida neque lectus in eros. Praesent sed fermentum leo. Vivamus in magna eget nulla condimentum vulputate. Donec eleifend blandit mi eget sollicitudin. Mauris vel cursus ante. Pellentesque dictum erat et libero mattis placerat. Quisque ac risus pretium, convallis lacus ut, venenatis nulla. Sed nibh mi, laoreet ac sem sed, placerat rhoncus nibh. Praesent vitae finibus nisl. Nunc nibh justo, faucibus eget turpis eget, iaculis vehicula quam. Suspendisse rhoncus leo sit amet urna dictum, ac vestibulum sapien ultrices. Vivamus vulputate, nunc in vehicula rhoncus, odio turpis convallis diam, et elementum velit ligula ut enim. Ut semper rhoncus massa nec blandit. Mauris viverra ante in auctor maximus.\n" +
                "\n" +
                "Nunc sagittis risus leo, eget rhoncus orci posuere sit amet. Donec imperdiet nunc convallis hendrerit molestie. Nam sit amet sollicitudin sem. Sed eu fermentum nunc. Curabitur consequat urna eget dapibus posuere. Pellentesque eu diam accumsan, imperdiet tellus vel, vestibulum risus. Phasellus lobortis erat dui, at tempus turpis mattis sed. Cras sit amet lectus eget enim ornare semper. Donec id velit scelerisque, efficitur augue eget, gravida orci. Vestibulum eleifend, nunc ac tristique porta, massa ipsum imperdiet ipsum, at facilisis orci ex eu augue. Mauris non odio sit amet nisl tristique venenatis. Donec sit amet blandit tellus.\n" +
                "\n" +
                "Ut nec lorem mi. Aenean sed erat nec est aliquet tincidunt. Nam ultrices lorem orci, a auctor ipsum tempus congue. Nullam sagittis magna dui, sed aliquet massa mollis sed. Donec pellentesque augue velit, eu malesuada neque bibendum imperdiet. Nunc lobortis nibh vitae odio scelerisque, quis sollicitudin tortor elementum. Vestibulum lobortis sodales leo, eu condimentum elit pretium at. Aliquam aliquam varius lectus in blandit. Duis pharetra turpis vel turpis euismod, tempus cursus diam sagittis. Fusce molestie lorem non odio finibus, eget rhoncus lorem ultricies. Cras fermentum ligula id sagittis efficitur. Nullam et turpis quis tortor maximus sollicitudin at eget libero. Nulla vestibulum, neque euismod finibus interdum, augue arcu vulputate mauris, quis faucibus ipsum augue ac lorem. Quisque augue sem, commodo a justo a, facilisis facilisis mauris.\n" +
                "\n" +
                "Sed ac tellus ut purus malesuada gravida. Suspendisse et nibh commodo, molestie urna eu, aliquet nulla. Aenean fermentum vitae sapien quis pretium. Nullam in dui interdum, porta nisl ut, ornare massa. Suspendisse vitae vulputate lorem, sed iaculis leo. Suspendisse potenti. Nulla ullamcorper rutrum auctor.\n" +
                "\n" +
                "Aenean consectetur neque eu nisi viverra, ac viverra eros suscipit. Nullam facilisis placerat felis eget congue. Donec sit amet vestibulum eros. Mauris tincidunt tincidunt nisl, at dapibus magna hendrerit convallis. Etiam sodales nibh id risus accumsan, sed mollis lorem pharetra. Duis ornare odio at lectus auctor blandit. Nullam ac convallis ligula. Morbi et orci non metus accumsan consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sed metus a est mattis placerat vitae ac sapien. Morbi in felis varius purus consequat finibus. Cras tristique nibh sed turpis sollicitudin, pulvinar feugiat velit suscipit. Maecenas tellus lectus, blandit non ipsum at, accumsan aliquet elit. Aliquam non convallis ante. Nunc sit amet magna eget elit laoreet faucibus. Nulla sagittis id nibh eget facilisis.\n" +
                "\n" +
                "Suspendisse rhoncus congue dolor vitae fermentum. Maecenas eget lorem nunc. In id arcu efficitur erat lobortis maximus. Maecenas rutrum eros at rutrum tincidunt. Praesent velit urna, mollis at rhoncus id, venenatis at tortor. Pellentesque euismod elit rutrum nisi pellentesque sodales. Mauris auctor quam ipsum, id vestibulum quam condimentum sed.\n" +
                "\n" +
                "Pellentesque in neque consectetur, feugiat elit id, venenatis dui. Quisque consequat vel diam quis auctor. Cras vel scelerisque est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras pharetra ante vel ante sollicitudin, vel euismod tortor iaculis. Morbi quis euismod nisl, vel pulvinar arcu. Nullam ut sagittis risus. Sed ut enim odio. Donec ut ligula tristique, ullamcorper ipsum non, blandit sem. Maecenas sed felis magna. Nulla eget metus dictum, ullamcorper ex at, tempus odio. Donec at neque at lacus sagittis facilisis in id leo. Curabitur facilisis dignissim rutrum. Proin suscipit, nisl nec cursus maximus, erat magna tempus magna, hendrerit blandit turpis odio tincidunt nisl.\n" +
                "\n" +
                "Phasellus urna mauris, dictum a condimentum ut, scelerisque non ex. Fusce at odio rhoncus massa iaculis tristique at ac dolor. Vivamus porttitor varius tempus. Suspendisse vitae tortor eu massa rhoncus vehicula. Pellentesque tincidunt ipsum quis dignissim dapibus. Nunc in massa et purus dapibus malesuada non a ante. Nulla bibendum nunc in fermentum pretium.\n" +
                "\n" +
                "Pellentesque condimentum rhoncus mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque nisi risus, fringilla non enim sit amet, ultrices laoreet nisl. Etiam vel pellentesque erat. Aenean suscipit ante at metus ornare lacinia. Duis sed venenatis quam. Donec sed justo quis turpis euismod porttitor. Vestibulum ullamcorper leo a vestibulum facilisis.\n" +
                "\n" +
                "Nunc elit sem, suscipit et turpis et, facilisis mollis mi. Nullam consectetur augue ac arcu fringilla, vel vulputate dui sagittis. Aliquam congue tristique lacus. Curabitur mattis condimentum erat non porta. Praesent pharetra urna orci, ut blandit magna pharetra eu. Sed maximus non ipsum eu faucibus. Morbi a pharetra elit. Pellentesque in odio neque.\n" +
                "\n" +
                "Phasellus gravida orci ex, eu pellentesque dolor accumsan a. Aenean fringilla justo a nisl cursus feugiat. Duis fermentum neque in ipsum laoreet mollis. Maecenas et nulla id ligula maximus ornare. Aenean viverra et neque ac mattis. Ut feugiat facilisis nibh, eget fringilla mauris fermentum fermentum. Praesent quis dui id libero tristique molestie in vel ex. In hac habitasse platea dictumst. Donec ante nulla, elementum non tellus quis, luctus viverra mi. Quisque sed urna purus. Cras suscipit eros ligula, non rhoncus arcu pulvinar ut. Phasellus ut risus lacus. Fusce ut luctus lacus. Duis metus mauris, sollicitudin non malesuada nec, tincidunt at orci. Sed in lorem at nunc ornare rhoncus. Nulla eget molestie orci, ut mattis velit.\n" +
                "\n" +
                "Morbi sit amet nisi mattis, dictum tortor ac, imperdiet ipsum. Donec ultricies nulla eget tempor vestibulum. Aenean vulputate nulla vestibulum nulla lacinia, pellentesque ullamcorper tortor blandit. Etiam dui quam, ultrices quis scelerisque a, consequat non diam. Praesent scelerisque ipsum quis ipsum eleifend imperdiet. Sed eget libero eget dui molestie bibendum. Mauris ipsum diam, eleifend ac convallis eget, facilisis quis libero. Suspendisse dapibus diam non malesuada molestie. Nunc iaculis efficitur risus, vitae eleifend arcu interdum pellentesque. Nam congue risus ac turpis dapibus, in pretium nulla scelerisque. Mauris nec hendrerit urna. Duis sit amet consequat massa. Sed in felis et libero vehicula porttitor sit amet vel justo. Nullam turpis diam, pretium egestas purus sed, vehicula egestas est. Aenean luctus nisi sem, vitae porttitor arcu lacinia vitae. Donec eros velit, fringilla id tincidunt sit amet, iaculis at metus.\n" +
                "\n" +
                "Quisque nec fermentum nisi. Vestibulum tortor nibh, pretium vitae orci a, congue egestas risus. In hac habitasse platea dictumst. Sed sagittis libero id condimentum pretium. Nunc ultricies dui orci, at gravida nunc lobortis a. Vivamus laoreet ultricies dapibus. Vestibulum maximus augue eget ultricies vehicula. Vivamus ullamcorper imperdiet risus sit amet mollis.\n" +
                "\n" +
                "Nulla sit amet odio in felis vulputate molestie. Proin ultricies ante lorem, nec imperdiet velit efficitur vitae. Sed a sem tellus. Duis gravida molestie ullamcorper. Duis quis sem in lacus mollis dignissim. Pellentesque ornare mattis cursus. Nullam ac vestibulum quam.\n" +
                "\n" +
                "Proin ut libero nec mi tincidunt cursus quis vitae leo. Maecenas elementum bibendum massa, quis auctor nisl venenatis non. Quisque malesuada ligula neque, sed luctus purus auctor vel. Phasellus tempor, tortor quis luctus elementum, diam leo molestie urna, a euismod metus lacus id massa. Cras nec purus et est vehicula commodo vitae et magna. Nullam placerat pulvinar urna, vel congue nisl vestibulum eu. Nulla luctus metus nisi, vel eleifend quam gravida vitae. Sed efficitur et risus eu venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempor felis sit amet lorem iaculis cursus. Ut est mauris, imperdiet quis lorem quis, convallis ornare odio. Cras mattis maximus rhoncus. Duis condimentum ut felis vel convallis. Pellentesque elementum euismod est sit amet viverra.\n" +
                "\n" +
                "In eleifend eleifend leo. Nunc nec quam a lorem semper consectetur a et sem. Duis libero odio, rutrum eu laoreet et, facilisis sed velit. Nunc ut feugiat massa. Vestibulum at condimentum neque. Duis eget nunc id erat interdum euismod. Quisque eu feugiat eros, at sollicitudin risus. Maecenas hendrerit risus malesuada laoreet bibendum.\n" +
                "\n" +
                "Curabitur tempor scelerisque massa vitae porttitor. Duis sodales venenatis elementum. Donec iaculis felis turpis, sit amet consequat enim volutpat vitae. Vivamus et sollicitudin nunc. In et commodo urna. Etiam blandit auctor viverra. Nullam posuere, sapien eu auctor viverra, magna libero dignissim ipsum, ut pulvinar justo odio blandit ex. Ut rhoncus in eros eget mattis.\n" +
                "\n" +
                "Donec a massa a augue venenatis euismod eu nec diam. Curabitur egestas, mi at fringilla tincidunt, quam diam pulvinar nisl, eu sagittis felis sapien a ex. Aenean hendrerit ante pellentesque, eleifend nisl ac, lacinia ipsum. Donec tristique et augue sed bibendum. Curabitur tempor metus augue, ac vestibulum odio volutpat eu. Curabitur gravida aliquet lacus. Praesent vulputate, ante eu accumsan efficitur, nibh velit semper lacus, id convallis enim est non est. Curabitur sagittis lacus a interdum mollis. Curabitur vitae cursus tortor. In lobortis arcu in interdum egestas. Nunc tellus lacus, vulputate eu sem ac, malesuada viverra sem.\n" +
                "\n" +
                "Sed quis enim tellus. Curabitur imperdiet feugiat vehicula. Aliquam condimentum, justo in molestie mollis, ex lorem scelerisque dui, nec ornare mi sem a ante. Praesent in hendrerit est, ac luctus purus. Aenean id diam malesuada metus luctus accumsan. Pellentesque consequat tortor cursus dictum mattis. Pellentesque vehicula pharetra nulla ut malesuada.\n" +
                "\n" +
                "Etiam ligula mauris, maximus nec nisi eget, sagittis pellentesque quam. Sed rutrum mauris vitae ligula eleifend tincidunt. Etiam eget mattis turpis. Suspendisse non elementum dui, sit amet tristique tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Cras ut ante sed nulla accumsan molestie. Integer id augue nec nunc volutpat rhoncus. Cras varius, nunc ut commodo imperdiet, enim velit volutpat metus, ut scelerisque purus elit at risus. Sed maximus eleifend lectus, eu imperdiet enim pulvinar eu. Quisque tincidunt hendrerit justo, elementum condimentum ex volutpat vitae. Quisque ante ligula, faucibus eu nisi in, pretium rutrum felis.\n" +
                "\n" +
                "Pellentesque lectus augue, tempus viverra pulvinar vel, mattis sed metus. Integer ut diam mauris. Suspendisse quis lectus eget nunc sollicitudin pretium et vel arcu. Cras volutpat, ipsum quis cursus gravida, metus urna feugiat diam, eget blandit orci velit sit amet nibh. Nullam sit amet porta mauris, eu cursus justo. Phasellus commodo leo tortor, ut sollicitudin nulla lobortis vel. Nullam varius non diam id fringilla. Aenean mattis, urna nec pellentesque pretium, tortor magna ultrices nulla, nec sollicitudin nibh nisl non orci. Quisque at ultrices erat. Fusce quis mi nulla. Nullam euismod turpis eget faucibus egestas.\n" +
                "\n" +
                "Nulla dictum aliquet iaculis. Vivamus interdum molestie pulvinar. Sed viverra nunc eu pulvinar lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras rutrum placerat sem, non laoreet augue gravida non. Maecenas metus felis, facilisis et dignissim eu, rhoncus nec ex. Sed imperdiet, ipsum sed consectetur gravida, mi dui condimentum neque, sed bibendum nisl enim ac lorem. Donec at dolor dignissim, pellentesque magna a, dictum magna. In enim erat, tempor et mattis in, tristique id purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris a lorem convallis, maximus enim et, fringilla nisi. In arcu erat, molestie non nibh sit amet, congue feugiat felis. Ut eget lacinia libero. Donec ut lorem in turpis fermentum tempor.\n" +
                "\n" +
                "Duis tempor ante id enim volutpat lacinia. Nunc posuere massa at nisi mollis gravida. Fusce et ipsum non nisl feugiat placerat. Maecenas luctus velit eu tellus aliquam semper. Sed ligula turpis, elementum in fermentum nec, blandit in purus. Etiam luctus sapien lacus, nec porttitor elit pulvinar eget. Suspendisse in eros neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");

    }


    public static void count(String a) {

        WordCounter counter = new WordCounter();

        counter.count(a);

        counter.treeForming();

        counter.binaryCalculations();
    }


}



